{
    'name': 'Accounting Reports',
    'category': 'Website',
    'summary': 'Account Reports in Web pages',
    'website': 'https://www.credativ.com',
    "sequence": 3,
    'version': '1.0',
    'description': """
        """,
    'author': 'test',
    'depends': ['website', 'mail'],
    'data': [
        'data/report_paperformat.xml',
        'security/ir.model.access.csv',
        'account_view.xml',                
        'website_account_report.xml',
        'views/website_profitloss.xml',
        'views/website_profitloss_backend.xml',
        'views/website_balancesheet.xml',
        'views/website_balancesheet_backend.xml',
        'views/website_trailbalance.xml',
        'views/website_trailbalance_backend.xml',
        'views/website_cashflow_statement.xml',
        'views/website_cashflow_statement_backend.xml',
        'views/report_cashflow_statement.xml',
        'wizard/account_report_general_ledger_view.xml',
        'views/report_generalledger.xml',
    ],
    'qweb': ['static/src/xml/*.xml'],
    'images': [
        'static/description/website_account_banner.jpg',
    ],
    'installable': True,    
    'auto_install': False,
    'application': True,
}
